### ISSUE TITLE
definitions question

### ISSUE THREAD

**Issue by manderss99** [cardigann/cardigann#138]
I'm trying to implement a new indexer and have problem with date

WARN[0005] Row #1 has unparseable time "18/07/2016" in date  site=xxx
WARN[0005] Row #2 has unparseable time "17/07/2016" in date  site=xxx
WARN[0005] Row #3 has unparseable time "16/07/2016" in date  site=xxx

the indexer uses d/m/y, how can I parse this?

**Comment by mmarquezs** [comment]
You can use a filter, you can check the filters available here:
https://github.com/cardigann/cardigann/blob/master/indexer/filters.go

In this case the one to use would be timeparse/dateparse (they are the same one):
https://github.com/cardigann/cardigann/blob/master/indexer/filters.go#L36

This filter uses the library time of go to parse the time/date using the function Parse passing it a layout:
https://golang.org/pkg/time/#Parse

The layout in this case which I'm already using it myself in a definition I'm making is this:
`02/01/2006`

Finally here goes an example of my definition with the filter:

```
date:
        selector: td:nth-child(5)
        filters:
          - name: dateparse
            args: "02/01/2006"
```
