### ISSUE TITLE
Add support for European time formats

### ISSUE THREAD

**Issue by kaso17** [cardigann/cardigann#207]
Many European trackers are using a day first time format instead of the US month first format.

One example is #127 (comment)

Currently fuzzytime is using the USContext always, this should be configurable

**Comment by mmarquezs** [comment]
You can already do this with filters, for dd/mm/yyyy this example works:

 ```
     date:
        selector: td:nth-child(5)
        filters:
          - name: dateparse
            args: "02/01/2006"
```
