### ISSUE TITLE
Indexer Request: TorrentBytes

### ISSUE THREAD

**Issue by shiftcodeYT** [cardigann/cardigann#81]
### EN

**Comment by mmarquezs** [comment]
I have this one started, the only missing part  I think is the categories. 
If somebody wants to use it as it is or finish it, here it's  copy, if not well I will try to finish it soon.
https://gist.github.com/mmarquezs/5a2b85d84f3376b959aeb6f73afb16b4

**Comment by lxt2** [comment]
Categories is always the most painful bit, I wonder if we could write up a doc so that non-technical contributors could provide the category map.

**Comment by mmarquezs** [comment]
I have done the categories but I had a problem, sometimes there are torrents without category, so there isn't the element I need to get the category, so the selector fails and doesn't pass the test.

For now I'm doing it like this:
```
 category:
        selector: td:nth-child(1) a,td:nth-child(2) a
        attribute: href
        filters:
          - name: regexp
            args: "browse\\.php\\?cat=(\\d+)|(.*)"
```

This way if it doesn't find the url of the category it takes the url of the download this way the selector doesn't fail.Then I modified the regex so if it doesn't find the category it returns something so it doesn't fail, that something it will be the full url and it wont match any category so it will return category 0.This way it doesn't fail the test and the other files get the categories but it's an ugly hack. 

I did a pullreuqest: https://github.com/cardigann/cardigann/pull/100
