### ISSUE TITLE
Adding immortalseed.me

### ISSUE THREAD

**Issue by subzero79** [cardigann/cardigann#85]
This is my current yml for immortalseed, I still haven't been able to catch the test error, ratio and other annoyances like browsing in the browse.php page is different url from search. Also they implement some sort of highlight entry when torrent is popular which breaks the search. 

```
---
  site: immortalseed
  name: Immortalseed
  description: "TV Series anyone?"
  language: en-us
  links:
    - https://immortalseed.me/

  caps:
    categories:
      35: Books
      25: PC/Games    #TV/DVD-R
      14: Movies
      32: Movies
      7: TV/Sport
      48: TV/SD
      6: TV
      32: TV/Anime
      31: TV
      16: Movies/HD
      30: Audio
      47: TV/SD
      9: TV/SD
      22: Books
      8: TV/HD
      4: TV

    modes:
      tv-search: [q, season, ep]

  ratio:
    path: /browse.php
    selector: #top > div.padding > span:nth-child(2)


  login:
    path: /takelogin.php
    method: post
    inputs:
      username: "{{ .Config.username }}"
      password: "{{ .Config.password }}"



  search:
    path: /browse.php?do=search
    inputs:
      keywords: "{{ .Query.Keywords }}"
      include_dead_torrents: yes
      category: 0
      search_type: t_name

    rows:
      selector: "#sortabletable > tbody > tr:not(tr:nth-child(1))"
    fields:
      title:
        selector: div:nth-child(2) > div:nth-child(1)
      category:
        selector: td.unsortable2 > a
        attribute: href
        filters:
          - name: querystring
            args: category
      download:
        selector: td:nth-child(3) > a:nth-child(2)
        attribute: href
      size:
        selector: td:nth-child(5)
      seeders:
        selector: td:nth-child(7)
      leechers:
        selector: td:nth-child(8)
      date:
        selector: td:nth-child(n) > div:nth-child(3)
```

If anyone is interested let me know, @lxt2 I send you access some weeks ago, don't know if it worked or not.
