### ISSUE TITLE
Modify indexer definition format to use inline javascript instead of golang templates

### ISSUE THREAD

**Issue by lxt2** [cardigann/cardigann#88]
Based on discussion in #4 with @kaso17, it would be great to have the indexer definition format usable in Jackett. Finding a .NET implementation of the golang templates seems unlikely, so instead we are going to look at moving the current golang template blocks to javascript. 

For examples in https://github.com/cardigann/cardigann/blob/master/definitions/iptorrents.yml#L87:

```yaml
  search:
    path: "/t"
    inputs:
      $raw: "{{range .Categories}}{{.}}&{{end}}q={{ .Query.Keywords }}"
```

would be come:

```yaml
  search:
    path: "/t"
    inputs: !javascript |
      var values = { "q": $keywords }
      Object.keys($categories).map(function(k) { encodeURIComponent(k) }).join('&');
```

The !javascript indicates what follows should be interpreted as JS, the `|` signifies a literal block in YAML. Then the variables that start with `$` are provided as context. 

Thoughts @kaso17?
